### ISSUE TITLE
Tarefa 01 - Adicionado página Markdown de <kaelsilva>

### ISSUE THREAD

**Issue by kaelsilva** [tacianosilva/eng-software-20205#5]
**Descrição das tarefas aqui:** https://docs.google.com/document/d/1q1S_LuPD-_pQfHCqOSVtZyJcqi9UWRqSbBYxOwhK-u8/edit

**Comment by kaelsilva** [comment]
Não é possível editar as issues (assign, label, project, etc.), @tacianosilva .

**Comment by tacianosilva** [comment]
A tarefa foi respondida corretamente, deveria ter comentado na issue no github e detalhar um pouco mais as respostas na página MarkDown. Poderia ter colocado os links/referências consultados ao fazer a tarefa.
